Repository sendsay-ru/sendsay-docs, pull requests merged in 2024-06, with the labels that each got.

#292 fix(sendsay-docs): hide carrot-quest-chat in data-iframe mode
  e2e/smoke.spec.ts
  src/css/custom.css
Labels: PR: Needs Code Review 🔥

#294 fix(sendsay-docs): edit amocrm
  docs/integrations/integration-with-amocrm.mdx
  static/img/integrations/integration-with-amocrm/api-key.png
Labels: PR: Code Accepted, PR: Design Awesome 👌

#295 fix(sendsay-docs): edit proscript
  docs/proscript/proscript-in-a-nutshell.md
Labels: PR: Code Accepted, PR: Design Awesome 👌

#297 fix(sendsay-docs): edit workflows
  docs/automations/automation-with-workflows/workflow-blocks.mdx
  docs/automations/automation-with-workflows/workflow-guide.mdx
  static/img/automations/automation-with-workflows/workflow-blocks/get-out-of-another-workflow.png
  static/img/automations/automation-with-workflows/workflow-blocks/parallel-workflow.png
  static/img/automations/automation-with-workflows/workflow-blocks/restart-the-workflow.png
  static/img/automations/automation-with-workflows/workflow-blocks/workflow.png
Labels: PR: Code Accepted

#296 fix(sendsay-docs): add updates june 2024
  docs/updates/list/2024/updates-june-2024.mdx
  docs/updates/list/index.mdx
  i18n/en/docusaurus-plugin-content-docs/current/updates/list/2024/updates-june-2024.mdx
  static/img/updates/2024/updates-june-2024/get-out-of-another-workflow.png
  static/img/updates/2024/updates-june-2024/invoice.png
  static/img/updates/2024/updates-june-2024/mail-notifications.png
  static/img/updates/2024/updates-june-2024/order.png
  static/img/updates/2024/updates-june-2024/parallel-workflow.png
  static/img/updates/2024/updates-june-2024/product-is-in-stock.png
  static/img/updates/2024/updates-june-2024/requisites.png
  static/img/updates/2024/updates-june-2024/restart-the-workflow.png
  static/img/updates/2024/updates-june-2024/service-authorization.png
Labels: PR: Code Accepted
