Repository sendsay-ru/sendsay-docs, pull requests merged in 2024-09, with the labels that each got.

#315 fix(sendsay-docs): fix links
  config/redirects.json
  config/searchExcludeRoutes.json
  docs/videolessons/automations/how-to-automate-birthday-emails.mdx
  docs/videolessons/automations/how-to-create-birthday-series.mdx
  docs/videolessons/automations/how-to-create-welcome-series.mdx
  docs/videolessons/automations/how-to-set-autoimport.mdx
  docs/videolessons/email-campaigns/drag-and-drop-editor.mdx
  docs/videolessons/email-campaigns/how-to-create-a-campaign-with-attachment.mdx
  docs/videolessons/email-campaigns/how-to-personalize-campaigns.mdx
  docs/videolessons/subscribers/data-groups.mdx
  docs/videolessons/subscribers/how-to-create-a-segment.mdx
  docs/videolessons/subscribers/how-to-export-data.mdx
  docs/videolessons/subscribers/how-to-import-subscribers.mdx
  docs/videolessons/subscribers/signup-forms.mdx
Labels: PR: Code Accepted, PR: Design Awesome 👌

#316 fix(sendsay-docs): add updates
  docs/other-channels/mobile-push/how-to-connect-mobile-push.mdx
  docs/updates/list/2024/updates-august-2024.mdx
  docs/updates/list/index.mdx
  i18n/en/docusaurus-plugin-content-docs/current/updates/list/2024/updates-august-2024.mdx
  static/img/updates/2024/updates-august-2024/contact-limit-1.png
  static/img/updates/2024/updates-august-2024/contact-limit.png
  static/img/updates/2024/updates-august-2024/mobile-push.png
  static/img/updates/2024/updates-august-2024/post-request.png
  static/img/updates/2024/updates-august-2024/transaction-status.png
Labels: PR: Code Accepted, PR: Design Awesome 👌

#318 feat(sendsay-docs): add support link component
  src/components/SupportLink/SupportLink.module.css
  src/components/SupportLink/SupportLink.tsx
  src/components/SupportLink/index.ts
Labels: PR: Code Accepted, PR: Design Awesome 👌

#321 fix(sendsay-docs): fix links
  docs/automations/automation-with-workflows/workflow-blocks.mdx
  docs/automations/automations-by-behaviour/product-recommendations.md
  docs/ecom/domain-settings-for-links.mdx
  docs/ecom/ecom-statistics.mdx
  docs/ecom/ecom-triggers.mdx
  docs/ecom/how-to-connect-ecom.mdx
  docs/email-campaigns/create-your-campaign/how-to-send-email-campaign.md
  docs/email-campaigns/create-your-campaign/send-time-optimization.md
  docs/email-campaigns/create-your-campaign/topic-subscription.md
  docs/email-campaigns/settings/campaign-footer.md
  docs/email-campaigns/settings/email-authentication.md
  docs/email-campaigns/settings/how-to-connect-domain.md
  docs/email-campaigns/settings/warming-up-IP-address.mdx
  docs/faq/change-billing-plan.mdx
  docs/faq/checklist.md
  docs/faq/double-opt-in.md
  docs/faq/moderation.md
  docs/getting-started/getting-started-with-sendsay.md
  docs/getting-started/how-to-migrate-to-sendsay.md
  docs/integrations/how-to-send-campaigns-from-your-crm.md
  docs/integrations/smtp-gate.md
  docs/other-channels/mobile-push/how-to-connect-mobile-push.mdx
  docs/other-channels/sms/how-to-connect-sms.md
  docs/other-channels/telegram/how-to-connect-a-bot.md
  docs/other-channels/telegram/how-to-create-a-telegram-campaign.md
  docs/other-channels/vk/how-to-create-vk-campaign.md
  docs/other-channels/web-push/how-to-create-web-push-campaign.md
  docs/sendsay-api/how-to-send-campaign-with-api.md
  docs/statistics/where-to-track-statistics.md
  docs/subscribers/contacts/how-to-activate-inactive-contacts.md
  docs/subscribers/contacts/stop-lists.md
  docs/subscribers/import-and-export/how-to-prepare-file-for-import.md
  docs/updates/list/2020/updates-july-2020.mdx
  docs/updates/list/2024/updates-august-2024.mdx
Labels: PR: Code Accepted, PR: Design Awesome 👌

#319 fix(sendsay-docs): add new videolesson
  docs/integrations/integration-with-amocrm.mdx
  docs/videolessons/automations/integration-with-amocrm.mdx
  i18n/en/docusaurus-plugin-content-docs/current/videolessons/automations/integration-with-amocrm.mdx
Labels: PR: Code Accepted, PR: Design Awesome 👌

#322 fix(sendsay-docs): add segmentation
  docs/other-channels/mobile-push/how-to-connect-mobile-push.mdx
  docs/other-channels/mobile-push/how-to-create-mobile-push-campaign.mdx
  docs/other-channels/mobile-push/segmentation.mdx
  docs/other-channels/mobile-push/statistics.mdx
  docs/subscribers/lists-and-segments/what-is-segment.md
  i18n/en/docusaurus-plugin-content-docs/current/other-channels/mobile-push/segmentation.mdx
  static/img/other-channels/mobile-push/how-to-connect-mobile-push/HMS.png
  static/img/other-channels/mobile-push/segmentation/app-id.png
  static/img/other-channels/mobile-push/segmentation/mobile-push-segment.gif
  static/img/other-channels/mobile-push/segmentation/operating-system-segment-1.png
  static/img/other-channels/mobile-push/segmentation/operating-system-segment.png
  static/img/other-channels/mobile-push/segmentation/single-app-segment.png
  static/img/other-channels/mobile-push/segmentation/single-service-segment.png
Labels: PR: Code Accepted, PR: Design Awesome 👌

#323 fix(sendsay-docs) add how-to-create-sms-campaign
  docs/email-campaigns/create-your-campaign/how-to-send-email-campaign.md
  docs/other-channels/sms/how-to-connect-sms.mdx
  docs/other-channels/sms/how-to-create-sms-campaign.mdx
  docs/other-channels/vk/how-to-create-vk-campaign.md
  docs/other-channels/web-push/how-to-create-web-push-campaign.md
  i18n/en/docusaurus-plugin-content-docs/current/other-channels/sms/how-to-connect-sms.mdx
  i18n/en/docusaurus-plugin-content-docs/current/other-channels/sms/how-to-create-sms-campaign.mdx
  static/img/other-channels/sms/how-to-create-sms-campaign/how-to-create-a-sms-campaign.gif
  static/img/other-channels/sms/how-to-create-sms-campaign/how-to-limit-audience.png
  static/img/other-channels/sms/how-to-create-sms-campaign/how-to-personalize-sms.gif
  static/img/other-channels/sms/how-to-create-sms-campaign/how-to-select-sms-recipients.png
  static/img/other-channels/sms/how-to-create-sms-campaign/select-sms-recipients.png
  static/img/other-channels/sms/how-to-create-sms-campaign/sms-campaign-editor.png
  static/img/other-channels/sms/how-to-create-sms-campaign/sms-campaign-test.gif
  static/img/other-channels/sms/how-to-create-sms-campaign/sms-symbol-limit.png
  static/img/other-channels/sms/how-to-create-sms-campaign/sms-transliteration.gif
  static/img/other-channels/sms/how-to-create-sms-campaign/transfer-of-additional-data-sms.gif
Labels: PR: Needs Code Review 🔥, PR: Design Awesome 👌

#324 fix how-to-connect-sms.mdx
  docs/other-channels/sms/how-to-connect-sms.mdx
Labels: PR: Code Accepted

#325 fix(sendsay-docs): edit test copy
  docs/email-campaigns/create-your-campaign/a-b-testing.md
  docs/email-campaigns/create-your-campaign/amp-campaign.mdx
  docs/email-campaigns/create-your-campaign/drag-and-drop-editor.md
  docs/email-campaigns/create-your-campaign/how-to-send-email-campaign.md
  docs/email-campaigns/create-your-campaign/preheader.mdx
  docs/email-campaigns/create-your-campaign/web-version.mdx
  docs/email-campaigns/create-your-campaign/why-gmail-clips-emails.md
  docs/email-campaigns/personalization/how-to-send-multilanguage-email.mdx
  docs/email-campaigns/personalization/how-to-use-amocrm-data-in-campaigns.mdx
  docs/email-campaigns/settings/email-authentication.md
  docs/faq/checklist.md
  docs/getting-started/getting-started-with-sendsay.md
  docs/integrations/integration-with-email-on-acid.mdx
Labels: PR: Code Accepted, PR: Design Awesome 👌
